{
    "name": "ScoreBoard",
    "author": "hachkingtohach1",
    "api": [
        "4.0.0", 
    ],
    "version": "1.0",
    "main": "hachkingtohach1\\ScoreBoard\\ScoreBoard",
    "website": "https://watchshit.weebly.com/",
    "description": "Plugin ScoreBoard, software pocketmine_pmmp",
}