---
ScoreBoardType: "public"
    
ScoreBoardPublic:                      
    broad:
        title: "§l§eSCOREBOARD"    
        score:    
            - " §bYour Coins: %getmoney"
            - " §1 Line 2"
            - " §e Line 3"
        
ScoreBoardPrivate:                      
    1:
        world: "world"
        title: "§l§eSCOREBOARD"    
        score:    
            - " §bYour Coins: %getcoins"
            - " §1 Line 2"
            - " §e Line 3"